### ISSUE TITLE
Possible licensing issue with JUCE

### ISSUE THREAD

**Issue by eXpl0it3r** [yvanvds/yse-soundengine#1]
While @TexKiller was searching for a replacement of OpenAL for [SFML](https://github.com/LaurentGomila/SFML/), he stumbled up on YSE, which sounded interesting up to the point, where the whole audio input and output is handled via [JUCE](http://www.juce.com/). While [chatting](http://en.sfml-dev.org/forums/index.php?topic=16364.0) about the different licenses, it has come to my attention, that YSE might have a licensing issue.
My understanding ([1](https://github.com/yvanvds/yse-soundengine/blob/master/buildfiles/yse_static_library.jucer#L195), [2](https://github.com/yvanvds/yse-soundengine/wiki)) is that YSE uses JUCE for audio input/output. But if it does so, which version of JUCE does one have to use? Since nothing else is mentioned and this is an open source project, it seems logical to pick the open source version of JUCE. But by doing so, one chooses the GPL license, which was desinged to inject itself into user code, meaning if YSE uses the GPL JUCE, YSE would need to be GPL as well and couldn't use its Eclipse license.
If YSE was meant to be used with a commercial license of JUCE, it would be important to document this. Whether you could then release your code under the Eclipse license, is beyond my understanding of the legal situation (i.e. ask a lawyer).

I simply wanted to bring this issue to your attention. So what is your input on this?

If there's really a licensing issue, would it be possible to strip the JUCE bits and use "something" (not sure what) else?

**Comment by yvanvds** [comment]
Closing this issue because I haven't heard back from you and I don't have any time soon to switch to a non juce option myself.

**Comment by eXpl0it3r** [comment]
There wasn't anything from us to get back to you and ignoring the issue won't resolve the possible license violation, but then again it's your library...

**Comment by TexKiller** [comment]
I was talking to him about the issue via e-mail but got busy lately, eXpl0it3r... That is why he said that.

**Comment by yvanvds** [comment]
Ok, perhaps I was a bit overzealous. I meant that the discussion in her was closed because, like texKiller says, we all got a bit busy.

The 'issue' itself is not resolved, but I intend to implement a more flexible backend system during the summer, so that JUCE can be replaced with an other backend by means of a compiler option. (Other backends will probably not work on all platforms and have all features implemented, but it would be the most flexible solution.)

**Comment by al2950** [comment]
Just found YSE, and was very excited :), However just found this issue, which is really unfortunate :(. I appreciate you have no need to fix it, although it does severely limit who can use YSE and therefore contribute to it, but could you outline the areas of your codebase that would need to be re-written to remove JUCE so someone, maybe me, can have a head start if they wanted to look at it?

**Comment by yvanvds** [comment]
Hi.

There are basically two places where JUCE is currently needed: reading audio files in different formats (should at least support WAV and OGG) and device output. The latter might be complicated to support: there are 5 platforms and most of them have multiple options. Like on Windows, you have directsound, WMA, ASIO and so on. That said, if we can support at least one platform without JUCE, it would be possible to make it into an optional compile flag.

On the other hand the issue is not actually that big. When you create open source software there's no problem. If you go commerially, you can still use YSE for free if you buy a JUCE license (which is not very expensive anyway).

**Comment by eXpl0it3r** [comment]
> reading audio files in different formats

OGG can either be done with libvorbis/libogg directly or by using [stb_vorbis](https://github.com/nothings/stb/blob/master/stb_vorbis.c), while WAV should be trivial. See for example SFML's source code.

> device output. The latter might be complicated to support: there are 5 platforms and most of them have multiple options. Like on Windows, you have directsound, WMA, ASIO and so on.

This is a non trivial task in my opinion, which is why most use JUCE, OpenAL or similar.

> When you create open source software there's no problem.

You still don't understand how the GPL license works...

**Comment by al2950** [comment]
Thanks for the info, ill have a look around. With a quick google search there might be a few options like PortAudio;
http://www.portaudio.com/docs/v19-doxydocs/api_overview.html

**Comment by yvanvds** [comment]
> You still don't understand how the GPL license works...

Be sure I know how it works. Look, I could easily change YSE license to GPL. It would not make any difference for me. But it would close the door for all commercial activity. If the JUCE developers have no problem with this having an eclipse license and you even buy a JUCE license to complement it, why would they suddenly have a problem when you release your product?

So let us close the license discussion once and for all. If someone makes the effort to replace some JUCE code, I'll gladly help to integrate it. If you don't use YSE because you think the license is an issue, so be it. Even if you take 90% of my code and use it without telling me, so be it. I don't really care. Even though I'm not gonna encourage that by making it public domain.

I'm just creating some code that interests me. And I put it online for other people's benefit, if any. And yeah, there is a license. Hell, I even published a game once with a license that prohibited nationalists from playing. Just for fun. In the end I have the right to do whatever I like, and not care about the consequenses.

**Comment by al2950** [comment]
Please please dont change your lib to GPL! 

These are just notes, mainly for me so I dont forget....
- libSndFile - Used for reading various audio file formats
  http://www.mega-nerd.com/libsndfile/

- libSoundIo - Another opensouce audio lib, but also lists other opensource alternatives
  http://libsound.io/

-libCinder may also be another option....
 https://libcinder.org

NB, Currently there are no open source libs, that I have found (except for JUCE), that will support all platforms that yse currently supports

If I was to create a fork that removed JUCE and replaced it with an alternative, but did not support IOS or Android, would this be helpful to anyone!?

**Comment by eXpl0it3r** [comment]
> Be sure I know how it works. Look, I could easily change YSE license to GPL. It would not make any difference for me. But it would close the door for all commercial activity. If the JUCE developers have no problem with this having an eclipse license and you even buy a JUCE license to complement it, why would they suddenly have a problem when you release your product?

Well my comment was in regards to: "When you create open source software there's no problem". You have a problem as long as you don't make your open source software also use the GPL license, including making a fork of YSE and putting that under GPL first.

That's the whole "problem" with GPL. As soon as your code touches and GPL code, your code becomes infect and **has** to be released under GPL as well.

But as you said, you probably can release your code under the Eclipse license in the assumption that everyone uses JUCE's commercial license, but then you have to explicitly state that.

> NB, Currently there are no open source libs, that I have found (except for JUCE), that will support all platforms that yse currently supports

[SFML](https://github.com/SFML/SFML) supports Windows, Linux, OS X and experimentially Android as well as iOS by utilizing OpenAL. OpenAL itself is under LGPL meaning SFML's zlib-licensed source base can only use it as a shared library. Fortunately iOS as well as Android come with a default OpenAL API. And as a final note you can use SFML's audio module without using the graphics module if you're only interested in audio.

**Comment by yvanvds** [comment]
> If I was to create a fork that removed JUCE and replaced it with an alternative, but did not support IOS or Android, would this be helpful to anyone!?

It would be fine by me. Although I still prefer a compiler directive, making JUCE optional. That seems like the most flexible solution for everyone because then I can add your alternative back in the original code. Which will be easier when new features are added.

**Comment by yvanvds** [comment]
> But as you said, you probably can release your code under the Eclipse license in the assumption that everyone uses JUCE's commercial license, but then you have to explicitly state that.

That is explained in the file `COPYING' in the root of the project.
