### ISSUE TITLE
Building yse for visual studio

### ISSUE THREAD

**Issue by grannyte** [yvanvds/yse-soundengine#2]
I just found about yse and it really looks like the library I need for my game but I'm not able to build yse and mos the issue seem to be around configuring juce and liking yse against it. 

Is there a tutorial or anything about this?

**Comment by yvanvds** [comment]
Hi. I haven't made a tutorial just yet. (It's really considered beta software, although I haven't had any real bugs for a long time.)

Of course you will have to build juce and the introjucer first. After that it should be as easy as opening buildfiles/yse_static_library.jucer or dll/yse_dll.jucer with the introjucer. You can open visual studio with everything set from within the introjucer project.

To help you more, I would need some more information about the errors you get. One thing that comes to mind is that the JUCE library headers have changed since I've last downloaded them. It's been a while. I don't have time to test that theory today though.

**Comment by yvanvds** [comment]
Hello, I've just released a binary on github. Don't know if you're still interested, but at least this issue can be closed now.

**Comment by grannyte** [comment]
Yes i'm still interested does your release suport x64?

I have succeded in compiling YSE after opening the issue but i have a variety of odities and issues when using it so i'll take a look at your release when i can download it later today.

**Comment by yvanvds** [comment]
Ok. Which platform do you mean? The macOS binary (i just added it) is x64. Windows is probably 32 bit, but i could look into creating a 64 bit version if necessary. Right now, adding binary releases are my first priority. I don't have a lot of experience with creating releases and such, so it might get a bit messy. I'll adjust while I'm working on them.
