### ISSUE TITLE
which music format can i use in yse?

### ISSUE THREAD

**Issue by woc2006** [yvanvds/yse-soundengine#3]
I was failed to register an account in forum, so i post my question at here.
1. Which format can I use? can I use both mp3 and wav?
2. Can you provide binary distribution for ios and mac, i have some trouble in building them.

**Comment by yvanvds** [comment]
Hi. Sorry about the forum. It was only up for a day, but it is working now.

You can use wav, but you'll need ogg instead of mp3. This was done on purpose: ogg is just as good as mp3, but mp3 is patented. To avoid problems, I thought it would be best not to include it.

There is an old binary on the website: http://attr-x.net/yse 

I'll create a new one soon. (It's about time.)

**Comment by yvanvds** [comment]
Hey, I just added a first binary release for mac. Let me know if you have any trouble with it. The static library is tested with the console demo project. Getting these binary releases in order is my first priority now.

**Comment by adderly** [comment]
Well talking about mp3 files, i've seen many softwares using mp3 files with public licenses. It would be nice to have mp3 support, although ogg is awesome most audio is provided in mp3 format.

Haven't looked into the sources much, how difficult would it be to implement it?

**Comment by yvanvds** [comment]
This is from the JUCE source code:

> IMPORTANT DISCLAIMER: By choosing to enable the JUCE_USE_MP3AUDIOFORMAT flag and
>    to compile the MP3 code into your software, you do so AT YOUR OWN RISK! By doing so,
>    you are agreeing that ROLI Ltd. is in no way responsible for any patent, copyright,
>    or other legal issues that you may suffer as a result.
>
>    The code in juce_MP3AudioFormat.cpp is NOT guaranteed to be free from infringements of 3rd- party
>    intellectual property. If you wish to use it, please seek your own independent advice about the
>    legality of doing so. If you are not willing to accept full responsibility for the consequences
>    of using this code, then do not enable the JUCE_USE_MP3AUDIOFORMAT setting.

So I am reluctant to include it. It would not be difficult, but in my view it is easier to notice a file does not play when you load an mp3. Otherwise you might include mp3's by mistake, inadvertently leaving you with a patent issue. And there's lots of software to do batch conversions from mp3 to ogg.

**Comment by yvanvds** [comment]
Of course you can easily compile YSE with mp3 support yourself: open the dll or static library project in the introducer, go to modules -> juce_audio_formats en enable mp3 support. Save the project and recompile.

**Comment by adderly** [comment]
Ok im scared now. I've read a little about this licensing topic, and it is well justifiable why not to use mp3 in any place. Although i compiled with mp3 support to see, and it does not work apparently. 

 Just thinking here, as platforms provide mp3 support in this case IOS and Android. There could be a way to integrate that access so that the library (yse) access the audio pcm from the platform library itself?

In any case i will try to stay away from it. xD
