### ISSUE TITLE
Separate the audio processing from backends and file loaders?

### ISSUE THREAD

**Issue by mdsitton** [yvanvds/yse-soundengine#9]
In issue #7 it is mentioned that some (including me) are not liking the use of JUCE in this library. In issue issue #1 / issue #8 there is the licensing problem making this library essentially useless to anyone that doesn't have a commercial JUCE license. 

So i propose an alternative option, refactor the library and just stick to audio processing? There are plenty of libraries out there to handle audio output, and format loading. This would remove the need to add and maintain support for all of the various platforms/APIs and file formats.

So refactor the library to separate the core audio processing from the higher level stuff. Make the core of the library completely cross platform moving it into only a processing role. There would have to be a method of getting PCM audio data to and from the application for the various inputs and outputs. If you wanted to still provide the api you have now, you could use this "core" api under the hood.

I guess the downsides of this would be that it would move the api to being lower level...

And if you don't want to do this why not change the license to something GPL compatible, and let others try to take this on. Because I think a library like what is described here could take over the world.

**Comment by yvanvds** [comment]
Yes, that is one if the possibilities. I could provide a few callbacks for input and output and be done with it. 

I have also discussed the problem with a JUCE sales representative. With open source products, there are no problems as far as they are concerned. For closed source, they propose these options:

a. every developer buys a JUCE license themselves, but can apply for a reduced price since YSE only uses a minimal part of JUCE.

b. I buy one JUCE license myself. If developers don't want to spend money on their own license they can still use a binary release of YSE since it is covered by my commercial license.

One problem remains though: the newer JUCE versions need a lot of Java wrappers to work on Android. Which makes it almost impossible to develop for android without using the whole JUCE ecosystem. If I just stick to audio processing this would not be a problem, but for now it forces me to revert to an old JUCE version, which will probably become problematic in the long run.

So to wrap it up: callback functions with a standard implementation for JUCE and portaudio/libsndfile might be the best option. I will have to find some time to implement that though. I have a full time job and am also working on some other projects. Any major changes to YSE mostly have to wait until the next holiday :-)

**Comment by mdsitton** [comment]
Also I'm curious why are you so attached to the epl?

**Comment by yvanvds** [comment]
I'm not. I want a license which allows for commercial use, without making the code public domain. Epl seems to do the job. I don't have a good feeling about time spent on considering possible licenses, so I reserve for myself the right not to care.

**Comment by mdsitton** [comment]
Well to put something in the public domain you have to explicitly state that it's in the public domain. Any license including or no license(with no license no one can really use it since you provide no guidelines saying so) you still retain copyright ownership over of the code will full rights to do as you please. Generally most use the BSD 3-clause https://opensource.org/licenses/BSD-3-Clause

That is unless by public domain, what you really mean is that you want to have code sharing of all distributed derivatives. Preventing private forks of your code. For that I will have to do a bit more research. LGPL may be an option?

**Comment by mdsitton** [comment]
Plus another option could be to dual license under EPL and GPL.

**Comment by yvanvds** [comment]
Well, public domain goes a bit far. I don't want someone to 'steal' my code and charge money for it. But since you clearly know more about it, could you provide a real life example of a situation where epl would have negative consequences?

**Comment by mdsitton** [comment]
As far as I understand any application that uses any gpl code whether it's dynamically or statically linked is prohibited from also using EPL code. Just like gpl code is prohibited in closed source applications...

**Comment by mdsitton** [comment]
So after looking around it looks like the Mozilla Public License 2.0 is what you should use. https://www.mozilla.org/en-US/MPL/2.0/FAQ/
https://opensource.org/licenses/MPL-2.0

**Comment by Vienzzion** [comment]
come on guys lets make this work. good job mdsitton

**Comment by mdsitton** [comment]
I wish he would but, at this point i've given given up any plans of actually trying to use this library. There is the license issues. And what i'm actually looking for is what i wrote out in the initial post, and something that supports HRTF based 3D audio for headphone users. As far as I can tell this only does stuff for surround based systems, which don't generally support vertically positioned sound. :/

I've thrown some information together about how to do the stuff and at some point i'm going to look into implementing something for myself. (Probably wont happen soon though because i'm pretty busy)

**Comment by yvanvds** [comment]
Ok, I've changed the license to MPL.

Look, I think adding backends other than JUCE is a good idea. But I simply don't have much time at the moment. I will probably work on this during the summer.

By the way, vertically positioned sound is already supported. Virtual surround for headphones is on my list. There a few virtual binaural code examples out there that could be of use. Probably that's also something for during the summer.

**Comment by desertkun** [comment]
@yvanvds Any updates on this? Want to use YSE instead of standard libgdx module, but concerned about licensing.

**Comment by yvanvds** [comment]
>  I will probably work on this during the summer.

That means July & August :-)

**Comment by mdsitton** [comment]
@yvanvds Summer has come and gone :)

**Comment by yvanvds** [comment]
Yes, good point :-)

I got as far as abstracting audio output and provide an alternate backend with portaudio. But the input side (file reading) is not ready. Soon after I started working on that i got the lead on another project which is very time consuming. Nothing I can do about it. I just don't find enough spare time. 

Not saying it will never be done, because I will need YSE in another project next year. But right now I just can't do it. Sorry about that.

**Comment by yvanvds** [comment]
Hi! JUCE is removed from the new main branch. I am using portaudio and libsndfile now, and the code is structured in a way that adding new backends can't be hard. Unfortunately this also meant that the synth interface is on hold right now because that was the last part depending on JUCE.
